# Generated by Django 4.2.2 on 2023-06-22 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dish",
            old_name="dishName",
            new_name="restaurantName",
        ),
    ]
